config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pokemons#index"
  get '/pokemons', to: 'pokemons#index'
  get '/pokemons/:id', to: 'pokemons#show', as: 'details_pokemons'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  def index
    response = RestClient.get 'https://pokeapi.co/api/v2/pokemon/?limit=151'
    @pokemons = JSON.parse(response.body)['results']
  end

  def show
    id = params[:id]
    response = RestClient.get "https://pokeapi.co/api/v2/pokemon/#{id}"
    @pokemon = JSON.parse(response.body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokemon</title>
    <link rel="icon" href="/assets/favipoke.ico" type="image/x-icon">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pokemons/index.html.erb
<!-- app/views/pokemons/index.html.erb -->
<div class="pokemon-card" style="width: 50%; margin: 0 auto; display:block;">
<h1><%= image_tag 'pokedex.png', class: 'pokedex-image' %>Pokedéx Primeira Geração</h1>
</div>
<div class="row">
  <% @pokemons.each_slice(5) do |slice| %>
    <div class="col-md-2">
      <% slice.each do |pokemon| %>
        <%= link_to details_pokemons_path(pokemon['url'].split('/').last) do%>
            <div class="pokemon-card">
                 <img src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/<%= pokemon['url'].split('/').last %>.png" alt="<%= pokemon['name'] %>">
                 <p class="pokemon-name" style="text-decoration:none;"><%= pokemon['name'].capitalize %></p>
             </div>
         <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/pokemons/show.html.erb
<!-- app/views/pokemons/details.html.erb -->
<div class="pokemon-card" style="width: 50%; margin: 0 auto; display:block;">
  <img src="<%= @pokemon['sprites']['front_default'] %>" alt="<%= @pokemon['name'] %>">
   <img src="<%= @pokemon['sprites']['back_default'] %>" alt="<%= @pokemon['name'] %>">
  <h1><%= @pokemon['name'].capitalize %></h1>
</div>
<br/>
<div class='rounded'>
<table width='100%' style='border:1; border-color:black' >
    <tr class="tr-title">
      <td colspan=2><b>Características</b></td>
    </tr>
    <tr>
      <td class="tr-title" >Altura</td>
      <td><%= @pokemon['height'] %> ft</td>
    </tr>
    <tr>
      <td class="tr-title">Peso</td>
      <td><%= @pokemon['weight'] %> hg</td>
    </tr>
    <tr>
      <td class="tr-title">Tipo</td>
      <td>
      <br/>
       <% @names = @pokemon['types'].map { |typesPokemon| typesPokemon["type"]["name"] }  %>
       <% @names.each do |name| %>
          <%=name.capitalize%><br/>
       <% end%>
       <br/>
      </td>
    </tr>
    <tr>
      <td class="tr-title">Habilidades</td>
      <td>
      <br/>
       <% @abilities = @pokemon['abilities'].map { |abilitiesPokemon| abilitiesPokemon["ability"]["name"] }  %>
       <% @abilities.each do |ability| %>
          <%=ability.capitalize%><br/>
       <% end%>
       <br/>
      </td>
    </tr>
    <tr>
      <td class="tr-title">Itens</td>
      <td>
      <br/>
       <% @heldItens = @pokemon['held_items'].map { |itens| itens["item"]["name"] }  %>
       <% @heldItens.each do |item| %>
          <%=item.capitalize%>&nbsp;<img src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/<%=item%>.png"><br/>

       <% end%>
       <br/>
      </td>
    </tr>
</table>
</div>
<br/>
<br/>
  <%= link_to "Voltar para a Pokedéx", pokemons_path, class: "btn-back" %>